import { StyleSheet } from 'react-native';
import { GoldTheme } from '../../../../constants/GoldTheme';

export const chatHeaderStyles = StyleSheet.create({
  header: {
    elevation: 8,
    shadowColor: GoldTheme.gold.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  backButtonInHeader: {
    marginRight: 12,
  },
  backButtonGradient: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.3)',
  },
  chatAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    ...GoldTheme.shadow.gold,
  },
  chatAvatarText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: GoldTheme.text.inverse,
  },
  headerTextContainer: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: GoldTheme.text.primary,
    marginBottom: 6,
  },
  headerInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  memberCountBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.2)',
  },
  memberCountText: {
    fontSize: 12,
    color: GoldTheme.gold.primary,
    fontWeight: '600',
  },
  headerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.2)',
    zIndex: 100, // Ensure header buttons are above other elements
  },
  headerButtonText: {
    fontSize: 12,
    color: GoldTheme.gold.primary,
    marginRight: 4,
    fontWeight: '600',
  },
  headerPanel: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 215, 0, 0.2)',
  },
  headerPanelGradient: {
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  tabRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 16,
    backgroundColor: 'rgba(255, 215, 0, 0.05)',
    borderRadius: 12,
    padding: 4,
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  tabActive: {
    backgroundColor: 'rgba(255, 215, 0, 0.2)',
  },
  tabText: {
    fontSize: 12,
    color: GoldTheme.text.muted,
    marginLeft: 4,
    fontWeight: '500',
  },
  tabTextActive: {
    color: GoldTheme.gold.primary,
    fontWeight: '600',
  },
  tabContent: {
    minHeight: 140,
    maxHeight: 180, // Increased height to accommodate text properly
    paddingVertical: 12,
  },
  membersContainer: {
    flex: 1,
  },
  memberItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginVertical: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderRadius: 8,
  },
  memberAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    ...GoldTheme.shadow.small,
  },
  memberAvatarText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: GoldTheme.text.inverse,
  },
  memberName: {
    fontSize: 14,
    color: GoldTheme.text.primary,
    fontWeight: '500',
  },
  mediaScrollView: {
    flex: 1,
    paddingVertical: 12,
    minHeight: 120, // Ensure minimum height for proper text display
  },
  mediaThumbnail: {
    width: 80,
    height: 80,
    borderRadius: 8,
    marginRight: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  mediaVideoWrap: {
    width: 140,
    height: 100,
    marginRight: 12,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#000',
    alignSelf: 'flex-start',
  },
  mediaAudioWrap: {
    width: 200,
    height: 60,
    marginRight: 12,
    borderRadius: 8,
    backgroundColor: 'rgba(45, 45, 45, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.2)',
    padding: 6,
    alignSelf: 'flex-start',
  },
  emptyTabText: {
    fontSize: 14,
    color: GoldTheme.text.muted,
    textAlign: 'center',
    fontStyle: 'italic',
    paddingVertical: 30,
    paddingHorizontal: 20,
    flex: 1,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 30,
    paddingHorizontal: 20,
    flex: 1,
  },
  loadingText: {
    fontSize: 14,
    color: GoldTheme.text.muted,
    marginLeft: 8,
    fontStyle: 'italic',
  },
  errorText: {
    fontSize: 14,
    color: GoldTheme.error || '#FF6B6B',
    textAlign: 'center',
    fontStyle: 'italic',
    paddingVertical: 30,
    paddingHorizontal: 20,
    flex: 1,
    alignSelf: 'center',
  },
});
