import { StyleSheet } from 'react-native';
import { GoldTheme } from '../../../../constants/GoldTheme';

export const messageInputStyles = StyleSheet.create({
  inputContainer: {
    backgroundColor: GoldTheme.background.primary,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 215, 0, 0.2)',
  },
  mediaPreview: {
    backgroundColor: GoldTheme.background.card,
    margin: 8,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.2)',
  },
  mediaPreviewContent: {
    position: 'relative',
    alignItems: 'center',
  },
  previewImage: {
    width: 120,
    height: 120,
    borderRadius: 8,
  },
  videoPreview: {
    width: '100%',
    maxWidth: 280,
    height: 160,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#000',
    alignSelf: 'center',
    position: 'relative',
    marginVertical: 8,
  },
  videoPreviewOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  videoPreviewInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoPreviewText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '500',
    marginLeft: 6,
  },
  audioPreview: {
    width: '100%',
  },
  removeButton: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: GoldTheme.background.primary,
    borderRadius: 12,
    padding: 2,
  },
  fileInfoContainer: {
    marginTop: 8,
    alignItems: 'center',
  },
  fileName: {
    fontSize: 12,
    color: GoldTheme.text.secondary,
    textAlign: 'center',
  },
  messageInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: GoldTheme.background.secondary,
  },
  attachButton: {
    padding: 8,
    borderRadius: 20,
    marginRight: 12,
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.2)',
  },
  emojiButton: {
    padding: 8,
    borderRadius: 20,
    marginRight: 12,
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.2)',
  },
  micButton: {
    padding: 8,
    borderRadius: 20,
    marginRight: 12,
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.2)',
  },
  textInput: {
    flex: 1,
    backgroundColor: GoldTheme.background.card,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: GoldTheme.text.primary,
    maxHeight: 100,
    marginRight: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.2)',
  },
  sendButton: {
    borderRadius: 22,
    overflow: 'hidden',
  },
  sendButtonActive: {
    ...GoldTheme.shadow.gold,
  },
  sendButtonDisabled: {
    opacity: 0.5,
  },
  sendButtonGradient: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
  },
  disabledButton: {
    opacity: 0.5,
  },
  disabledInput: {
    opacity: 0.7,
  },
  uploadingText: {
    color: '#fff',
    fontSize: 10,
    marginTop: 2,
  },
  audioRecordingPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: GoldTheme.background.card,
    borderRadius: 12,
    padding: 12,
    marginHorizontal: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.2)',
  },
  audioRemoveButton: {
    marginLeft: 8,
    padding: 4,
  },
});
